export { default as Home } from './home'
export { default as Login } from './login'
export { default as Orders } from './orders'
export { default as Header } from '../components/header'
export { default as Footer } from '../components/footer'
export { default as Greeting } from '../components/greeting'
export { default as MiniCard } from '../components/miniCard'
export { default as RecentOrder } from '../components/recentOrder'
export { default as OrderList } from '../components/orderList'

export  const lableStyle = 'block text-[#ababab] text-lg font-medium'
export  const inputStyle = 'bg-[#1f1f1f] border border-gray-600 text-white text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 '